
name: Build Custom Bazzite Image
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        uses: ublue-os/bluebuild@v4
        with:
          containerfile: Containerfile
